version: '3.9'

services:
    backend:
        build: ./backend
        container_name: holdfast_backend
        ports:
            - "${BACKEND_PORT}:8080"
        restart: always

    frontend:
        build: ./frontend
        container_name: holdfast_frontend
        ports:
            - "${FRONTEND_PORT}:80"
        depends_on:
            - backend
        restart: always

    mysql_db:
        image: mysql:8.0
        container_name: holdfast_mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
